//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliWebR1.web {
    
    
    public partial class MatchHistory {
        
        /// <summary>
        /// template_currentmatchs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntelliWebR1.web.ko.template_currentmatchs template_currentmatchs;
        
        /// <summary>
        /// template_pastmatchs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntelliWebR1.web.ko.template_pastmatchs template_pastmatchs;
    }
}
